<#
.SYNOPSIS
    Certificate Deployment Script - Certificate
.DESCRIPTION
    Automated certificate deployment and replacement using PowerShell App Deployment Toolkit (PSADT) 4.x.
    
    Certificate Details:
    - Subject: C=NL
L=Den Haag
O=Brandmeester B.V.
OU=1052300
CN=Brandmeester B.V.
emailAddress=diederick.langenberg@srkrechtsbijstand.nl
    - Issuer: C=NL
ST=Zuid-Holland
O=Stichting Processen Verbaal
OU=SPV Certificate Authority
CN=Stichting Processen Verbaal CA Y26
emailAddress=info@stichtingpv.nl
    - Thumbprint: B12EA5114A425DC759F91D716B5F6008A9E0C5B6
    - Store: LocalMachine\My
    - Mode: Add only (Keep existing)
    
    Generated by: PSADT Script Generator (https://psadt.workplacebuilder.nl)
    Author: R.Lancel
    Date: 2026-01-28
.NOTES
    Toolkit: PowerShell App Deployment Toolkit (PSADT) v4.x
.LINK
    https://psappdeploytoolkit.com
#>

[CmdletBinding()]
Param (
    [Parameter(Mandatory=$false)]
    [ValidateSet('Install','Uninstall','Repair')]
    [String]$DeploymentType = 'Install',
    [Parameter(Mandatory=$false)]
    [ValidateSet('Interactive','Silent','NonInteractive')]
    [String]$DeployMode = 'Interactive',
    [Parameter(Mandatory=$false)]
    [switch]$AllowRebootPassThru = $false,
    [Parameter(Mandatory=$false)]
    [switch]$TerminalServerMode = $false,
    [Parameter(Mandatory=$false)]
    [switch]$DisableLogging = $false
)

Try {
    #---------------------------------------------------------------------------
    # VARIABLE DECLARATION
    #---------------------------------------------------------------------------
    $adtSession = @{
        AppVendor = 'C=NL
ST=Zuid-Holland
O=Stichting Processen Verbaal
OU=SPV Certificate Authority
Stichting Processen Verbaal CA Y26
emailAddress=info@stichtingpv.nl'
        AppName = 'Certificate'
        AppVersion = '2027'
        AppArch = 'x64'
        AppLang = 'EN'
        AppRevision = '01'
        AppProcessesToClose = @()
        AppScriptVersion = '1.0.0'
        AppScriptDate = '2026-01-28'
        AppScriptAuthor = 'R.Lancel'
        InstallName = 'Certificate Deployment'
        InstallTitle = 'Certificate - Certificate Deployment'
        DeployAppScriptFriendlyName = 'Certificate Certificate Deployment'
        DeployAppScriptVersion = '1.0.0'
        DeployAppScriptDate = '2026-01-28'
        DeployAppScriptParameters = $PsBoundParameters
    }
    
    # Certificate configuration
    $certificateFileName = "Brandmeester B.V..p12"
    $certificateThumbprint = "B12EA5114A425DC759F91D716B5F6008A9E0C5B6"
    $storeLocation = "Cert:\LocalMachine\My\My"
    
    #---------------------------------------------------------------------------
    # INITIALIZATION
    #---------------------------------------------------------------------------
    
    # Import PSADT module
    $adtModulePath = Join-Path -Path $PSScriptRoot -ChildPath "PSAppDeployToolkit\PSAppDeployToolkit.psd1"
    if (-not (Test-Path -Path $adtModulePath -PathType Leaf)) {
        Write-Error "PSAppDeployToolkit module not found at: $adtModulePath"
        Exit 1
    }
    
    Import-Module -Name $adtModulePath -Force -ErrorAction Stop
    
    # Initialize ADT session
    Initialize-ADTModule -ScriptDirectory $PSScriptRoot @adtSession
    
    Write-ADTLogEntry -Message "========================================" -Severity 1
    Write-ADTLogEntry -Message "CERTIFICATE DEPLOYMENT STARTED" -Severity 1
    Write-ADTLogEntry -Message "Certificate: C=NL
L=Den Haag
O=Brandmeester B.V.
OU=1052300
CN=Brandmeester B.V.
emailAddress=diederick.langenberg@srkrechtsbijstand.nl" -Severity 1
    Write-ADTLogEntry -Message "Mode: Add Only" -Severity 1
    Write-ADTLogEntry -Message "========================================" -Severity 1
    
    #---------------------------------------------------------------------------
    # PRE-INSTALLATION
    #---------------------------------------------------------------------------
    
    If ($DeploymentType -ieq 'Install') {
        Show-ADTInstallationWelcome -CloseProcesses 'none' -Silent
        
        Show-ADTInstallationProgress -StatusMessage "Preparing certificate deployment..."
        
        # Validate target store exists
        Write-ADTLogEntry -Message "Validating certificate store: $storeLocation" -Severity 1
        
        if (-not (Test-Path $storeLocation)) {
            Write-ADTLogEntry -Message "Certificate store not found: $storeLocation" -Severity 3
            Show-ADTInstallationPrompt -Message "Certificate store not found: $storeLocation" -ButtonRightText "OK" -Icon "Error"
            Exit-ADTInvocation -ExitCode 1
        }
        
        Write-ADTLogEntry -Message "Certificate store validated successfully" -Severity 1
    }
    
    #---------------------------------------------------------------------------
    # INSTALLATION
    #---------------------------------------------------------------------------
    
    If ($DeploymentType -ieq 'Install') {
        Show-ADTInstallationProgress -StatusMessage "Installing certificate..."
        
        $certFile = Join-Path -Path $adtDirFiles -ChildPath $certificateFileName
        
        # Verify certificate file exists
        if (-not (Test-Path $certFile)) {
            Write-ADTLogEntry -Message "Certificate file not found: $certFile" -Severity 3
            Show-ADTInstallationPrompt -Message "Certificate file not found: $certFile" -ButtonRightText "OK" -Icon "Error"
            Exit-ADTInvocation -ExitCode 1
        }
        
        Write-ADTLogEntry -Message "Certificate file found: $certFile" -Severity 1
        Write-ADTLogEntry -Message "Importing certificate to: $storeLocation" -Severity 1
        
        try {
            # Import certificate
            $securePassword = ConvertTo-SecureString -String "tPVf37afNSnrJ" -Force -AsPlainText
        Import-PfxCertificate -FilePath $certFile -CertStoreLocation "Cert:\LocalMachine\My\My" -Password $securePassword -Exportable -ErrorAction Stop
            
            Write-ADTLogEntry -Message "Certificate imported successfully" -Severity 1
            
            # Verify installation
            $newCert = Get-ChildItem -Path $storeLocation | Where-Object { $_.Thumbprint -eq $certificateThumbprint }
            
            if ($newCert) {
                Write-ADTLogEntry -Message "Certificate verification successful" -Severity 1
                Write-ADTLogEntry -Message "Subject: $($newCert.Subject)" -Severity 1
                Write-ADTLogEntry -Message "Thumbprint: $($newCert.Thumbprint)" -Severity 1
                Write-ADTLogEntry -Message "Valid until: $($newCert.NotAfter)" -Severity 1
                
                Show-ADTInstallationInfo -Message "Certificate installed successfully`nSubject: $($newCert.Subject)`nValid until: $($newCert.NotAfter)" -Icon "Information"
            } else {
                throw "Certificate verification failed - Certificate not found in store after import"
            }
        }
        catch {
            Write-ADTLogEntry -Message "Failed to install certificate: $($_.Exception.Message)" -Severity 3
            Show-ADTInstallationPrompt -Message "Failed to install certificate:`n$($_.Exception.Message)" -ButtonRightText "OK" -Icon "Error"
            Exit-ADTInvocation -ExitCode 1
        }
    }
    
    #---------------------------------------------------------------------------
    # POST-INSTALLATION
    #---------------------------------------------------------------------------
    
    If ($DeploymentType -ieq 'Install') {
        
        Write-ADTLogEntry -Message "Certificate deployment completed successfully" -Severity 1
        Show-ADTInstallationInfo -Message "Certificate deployment completed successfully" -Icon "Information"
    }
    
    #---------------------------------------------------------------------------
    # UNINSTALLATION
    #---------------------------------------------------------------------------
    
    ElseIf ($DeploymentType -ieq 'Uninstall') {
        Show-ADTInstallationWelcome -CloseProcesses 'none' -Silent
        
        Show-ADTInstallationProgress -StatusMessage "Removing certificate..."
        
        Write-ADTLogEntry -Message "Searching for certificate with thumbprint: $certificateThumbprint" -Severity 1
        
        try {
            $cert = Get-ChildItem -Path $storeLocation | Where-Object { $_.Thumbprint -eq $certificateThumbprint }
            
            if ($cert) {
                Write-ADTLogEntry -Message "Certificate found: $($cert.Subject)" -Severity 1
                Remove-Item -Path $cert.PSPath -Force -ErrorAction Stop
                Write-ADTLogEntry -Message "Certificate removed successfully" -Severity 1
                Show-ADTInstallationInfo -Message "Certificate removed successfully" -Icon "Information"
            } else {
                Write-ADTLogEntry -Message "Certificate not found (already removed)" -Severity 2
                Show-ADTInstallationInfo -Message "Certificate not found (already removed)" -Icon "Information"
            }
        }
        catch {
            Write-ADTLogEntry -Message "Failed to remove certificate: $($_.Exception.Message)" -Severity 3
            Show-ADTInstallationPrompt -Message "Failed to remove certificate:`n$($_.Exception.Message)" -ButtonRightText "OK" -Icon "Error"
            Exit-ADTInvocation -ExitCode 1
        }
    }
    
    #---------------------------------------------------------------------------
    # FINALIZATION
    #---------------------------------------------------------------------------
    
    Write-ADTLogEntry -Message "========================================" -Severity 1
    Write-ADTLogEntry -Message "CERTIFICATE DEPLOYMENT COMPLETED" -Severity 1
    Write-ADTLogEntry -Message "========================================" -Severity 1
}
Catch {
    Write-ADTLogEntry -Message "Error in certificate deployment: $($_.Exception.Message)" -Severity 3
    Show-ADTInstallationPrompt -Message "An error occurred during certificate deployment:`n$($_.Exception.Message)" -ButtonRightText "OK" -Icon "Error"
    Exit-ADTInvocation -ExitCode 1
}
Finally {
    Complete-ADTInvocation
}
