<#
.SYNOPSIS
    Certificate Deployment - Certificate_Brandmeester_B.V.
.DESCRIPTION
    Automated certificate deployment using PowerShell App Deployment Toolkit (PSADT) 4.1.8.
    
    Certificate Details:
    - Subject: C=NL
L=Den Haag
O=Brandmeester B.V.
OU=1052300
CN=Brandmeester B.V.
emailAddress=diederick.langenberg@srkrechtsbijstand.nl
    - Issuer: C=NL
ST=Zuid-Holland
O=Stichting Processen Verbaal
OU=SPV Certificate Authority
CN=Stichting Processen Verbaal CA Y26
emailAddress=info@stichtingpv.nl
    - Thumbprint: B12EA5114A425DC759F91D716B5F6008A9E0C5B6
    - Store: LocalMachine\My
    - Mode: Add only
    
    Generated by: PSADT Script Generator
    Author: R.Lancel
    Date: 2026-01-28
#>

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$SuppressRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)

##================================================
## MARK: Variables
##================================================

$adtSession = @{
    AppVendor = 'Brandmeester B.V.'
    AppName = 'Certificate_Brandmeester_B.V.'
    AppVersion = '2027'
    AppArch = ''
    AppLang = 'EN'
    AppRevision = '01'
    AppSuccessExitCodes = @(0)
    AppRebootExitCodes = @(1641, 3010)
    AppProcessesToClose = @()
    AppScriptVersion = '1.0.0'
    AppScriptDate = '2026-01-28'
    AppScriptAuthor = 'R.Lancel'
    DeployAppScriptFriendlyName = 'Certificate_Brandmeester_B.V. Certificate'
}

# Certificate configuration
$Script:certificateFileName = "Brandmeester B.V..p12"
$Script:certificateThumbprint = "B12EA5114A425DC759F91D716B5F6008A9E0C5B6"
$Script:storeLocation = "Cert:\LocalMachine\My"
$Script:oldCertThumbprints = @()

##================================================
## MARK: Functions
##================================================

function Install-ADTDeployment
{
    [CmdletBinding()]
    param()

    ##================================================
    ## MARK: Pre-Install
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

    Write-ADTLogEntry -Message "Starting certificate deployment" -Severity 1
    Write-ADTLogEntry -Message "Certificate: $Script:certificateThumbprint" -Severity 1
    Write-ADTLogEntry -Message "Target store: $Script:storeLocation" -Severity 1

    # Show progress
    Show-ADTInstallationProgress -StatusMessage "Installing certificate..."

    ##================================================
    ## MARK: Install
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

    try {
        # Validate target store
        if (-not (Test-Path $Script:storeLocation)) {
            throw "Certificate store not found: $Script:storeLocation"
        }

        # Get certificate file path
        $certFile = Join-Path -Path $adtSession.DirFiles -ChildPath $Script:certificateFileName
        if (-not (Test-Path $certFile)) {
            throw "Certificate file not found: $certFile"
        }

        Write-ADTLogEntry -Message "Installing certificate from: $certFile" -Severity 1

        # Remove old certificates if in replace mode
        if ($Script:oldCertThumbprints.Count -gt 0) {
            Write-ADTLogEntry -Message "Removing $($Script:oldCertThumbprints.Count) old certificate(s)" -Severity 1
            
            foreach ($oldThumbprint in $Script:oldCertThumbprints) {
                $oldCert = Get-ChildItem -Path $Script:storeLocation | Where-Object { $_.Thumbprint -eq $oldThumbprint }
                if ($oldCert) {
                    Remove-Item -Path $oldCert.PSPath -Force -ErrorAction Stop
                    Write-ADTLogEntry -Message "Removed old certificate: $oldThumbprint" -Severity 1
                } else {
                    Write-ADTLogEntry -Message "Old certificate not found (already removed): $oldThumbprint" -Severity 2
                }
            }
        }

        # Import new certificate
        $securePassword = ConvertTo-SecureString -String "tPVf37afNSnrJ" -Force -AsPlainText
        Import-PfxCertificate -FilePath $certFile -CertStoreLocation $Script:storeLocation -Password $securePassword -Exportable -ErrorAction Stop
        
        # Verify installation
        $newCert = Get-ChildItem -Path $Script:storeLocation | Where-Object { $_.Thumbprint -eq $Script:certificateThumbprint }
        if ($newCert) {
            Write-ADTLogEntry -Message "Certificate installed successfully" -Severity 1
            Write-ADTLogEntry -Message "Subject: $($newCert.Subject)" -Severity 1
            Write-ADTLogEntry -Message "Valid until: $($newCert.NotAfter)" -Severity 1
        } else {
            throw "Certificate verification failed - not found in store after import"
        }
    }
    catch {
        Write-ADTLogEntry -Message "Failed to install certificate: $($_.Exception.Message)" -Severity 3
        throw
    }

    ##================================================
    ## MARK: Post-Install
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

    Write-ADTLogEntry -Message "Certificate deployment completed successfully" -Severity 1
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param()

    ##================================================
    ## MARK: Pre-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"

    Write-ADTLogEntry -Message "Starting certificate removal" -Severity 1
    Write-ADTLogEntry -Message "Certificate thumbprint: $Script:certificateThumbprint" -Severity 1

    Show-ADTInstallationProgress -StatusMessage "Removing certificate..."

    ##================================================
    ## MARK: Uninstall
    ##================================================
    $adtSession.InstallPhase = $adtSession.DeploymentType

    try {
        $cert = Get-ChildItem -Path $Script:storeLocation | Where-Object { $_.Thumbprint -eq $Script:certificateThumbprint }
        if ($cert) {
            Remove-Item -Path $cert.PSPath -Force -ErrorAction Stop
            Write-ADTLogEntry -Message "Certificate removed successfully: $Script:certificateThumbprint" -Severity 1
        } else {
            Write-ADTLogEntry -Message "Certificate not found (already removed)" -Severity 2
        }
    }
    catch {
        Write-ADTLogEntry -Message "Failed to remove certificate: $($_.Exception.Message)" -Severity 3
        throw
    }

    ##================================================
    ## MARK: Post-Uninstall
    ##================================================
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"

    Write-ADTLogEntry -Message "Certificate removal completed" -Severity 1
}

##================================================
## MARK: Execution
##================================================

$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

# Import the module and instantiate a new session.
try
{
    # Import PSADT module
    if (Test-Path -LiteralPath "$PSScriptRoot\AppDeployToolkit\PSAppDeployToolkit.psd1" -PathType Leaf)
    {
        Get-ChildItem -LiteralPath "$PSScriptRoot\AppDeployToolkit" -Recurse -File | Unblock-File -ErrorAction Ignore
        Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\AppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.8' } -Force
    }
    else
    {
        Import-Module -FullyQualifiedName @{ ModuleName = 'PSAppDeployToolkit'; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.8' } -Force
    }

    # Open ADT session
    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch
{
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}

# Execute deployment
try
{
    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    $mainErrorMessage = "An unhandled error has occurred:`n$($_.Exception.Message)"
    Write-ADTLogEntry -Message $mainErrorMessage -Severity 3
    Close-ADTSession -ExitCode 60001
}
